app:
    resource: "@AppBundle/Resources/config/routing.yml"

app_extra:
    resource: "@AppExtraBundle/Resources/config/routing.yml"

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin